name: recipes_web
description: Recipes/Cookbook Mobile/Web Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  # redux: ^5.0.0
  # flutter_redux: ^0.10.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.11
  cached_network_image: ^3.1.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  flutter_jailbreak_detection: ^1.8.0
  connectivity: ^3.0.6
  intl: ^0.17.0
  toggle_switch: ^2.0.1
  get: ^4.6.5
  # platform_plus: ^4.2.0
  # pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
